import { Route } from '@angular/router';
import {
  ServiceTypesFacade,
  serviceTypesReducer,
  loadServiceTypes$,
  loadServiceTypesBatch$,
  loadServiceType$,
  createServiceType$,
  updateServiceType$,
  deleteServiceType$,
  ServicePlansFacade,
  servicePlansReducer,
  loadServicePlans$,
  loadServicePlansBatch$,
  loadServicePlan$,
  createServicePlan$,
  updateServicePlan$,
  deleteServicePlan$,
  SubscriptionsFacade,
  subscriptionsReducer,
  loadSubscriptions$,
  loadSubscription$,
  createSubscription$,
  cancelSubscription$,
  resumeSubscription$,
  CustomerProfilesFacade,
  customerProfilesReducer,
  loadCustomerProfile$,
  createOrUpdateCustomerProfile$,
  AvailabilityFacade,
  availabilityReducer,
  checkAvailability$,
  getAlternatives$,
  BackordersFacade,
  backordersReducer,
  loadBackorders$,
  retryBackorder$,
  cancelBackorder$,
  PricingFacade,
  pricingReducer,
  previewPricing$,
  InvoicesFacade,
  invoicesReducer,
  loadInvoices$,
  createInvoice$,
  UsageFacade,
  usageReducer,
  loadUsageSummary$,
} from '@forepath/framework/frontend/data-access-billing-console';
import { authGuard, adminGuard, identityAuthProviders, identityAuthRoutes } from '@forepath/identity/frontend';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';
import { BillingConsoleContainerComponent } from './container/container.component';
import { CatalogComponent } from './catalog/catalog.component';
import { SubscriptionsComponent } from './subscriptions/subscriptions.component';
import { BillingComponent } from './billing/billing.component';
import { BackordersComponent } from './backorders/backorders.component';

export const billingConsoleRoutes: Route[] = [
  {
    path: '',
    component: BillingConsoleContainerComponent,
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'subscriptions' },
      ...identityAuthRoutes,
      {
        path: 'catalog',
        canActivate: [authGuard, adminGuard],
        component: CatalogComponent,
        title: 'Service Catalog | Billing',
      },
      {
        path: 'subscriptions',
        canActivate: [authGuard],
        title: 'Subscriptions | Billing',
        children: [{ path: '', component: SubscriptionsComponent, pathMatch: 'full' }],
      },
      {
        path: 'billing',
        canActivate: [authGuard],
        component: BillingComponent,
        title: 'Billing | Billing',
      },
      {
        path: 'backorders',
        canActivate: [authGuard],
        component: BackordersComponent,
        title: 'Backorders | Billing',
      },
      { path: '**', redirectTo: 'subscriptions' },
    ],
    providers: [
      ...identityAuthProviders,
      ServiceTypesFacade,
      ServicePlansFacade,
      SubscriptionsFacade,
      CustomerProfilesFacade,
      AvailabilityFacade,
      BackordersFacade,
      PricingFacade,
      InvoicesFacade,
      UsageFacade,
      provideState('serviceTypes', serviceTypesReducer),
      provideState('servicePlans', servicePlansReducer),
      provideState('subscriptions', subscriptionsReducer),
      provideState('customerProfiles', customerProfilesReducer),
      provideState('availability', availabilityReducer),
      provideState('backorders', backordersReducer),
      provideState('pricing', pricingReducer),
      provideState('invoices', invoicesReducer),
      provideState('usage', usageReducer),
      provideEffects({
        loadServiceTypes$,
        loadServiceTypesBatch$,
        loadServiceType$,
        createServiceType$,
        updateServiceType$,
        deleteServiceType$,
        loadServicePlans$,
        loadServicePlansBatch$,
        loadServicePlan$,
        createServicePlan$,
        updateServicePlan$,
        deleteServicePlan$,
        loadSubscriptions$,
        loadSubscription$,
        createSubscription$,
        cancelSubscription$,
        resumeSubscription$,
        loadCustomerProfile$,
        createOrUpdateCustomerProfile$,
        checkAvailability$,
        getAlternatives$,
        loadBackorders$,
        retryBackorder$,
        cancelBackorder$,
        previewPricing$,
        loadInvoices$,
        createInvoice$,
        loadUsageSummary$,
      }),
    ],
  },
];
