# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
reviews:
  profile: 'assertive'
  request_changes_workflow: false
  high_level_summary: false
  poem: true
  review_status: true
  review_details: true
  auto_review:
    enabled: true
    drafts: false
    ignore_usernames: ['dependabot[bot]', 'semantic-release-bot']
chat:
  auto_reply: true
