services:
  frontend-portal-server:
    image: ghcr.io/forepath/agenstra-portal-server:latest
    pull_policy: never
    container_name: portal-server
    environment:
      # Frontend server configuration
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-4200}
      NODE_ENV: ${NODE_ENV:-production}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-en}
    ports:
      - '${PORT:-4200}:${PORT:-4200}'
    networks:
      - portal-network
    restart: unless-stopped

networks:
  portal-network:
    driver: bridge
