import { Route } from '@angular/router';
import {
  AgentsFacade,
  agentsReducer,
  authenticationReducer,
  cancelRun$,
  checkAuthentication$,
  clearChatHistoryOnCreateSuccess$,
  clearChatHistoryOnDeleteAllSuccess$,
  clearChatHistoryOnDeleteSuccess$,
  clearChatHistoryOnUpdateSuccess$,
  ClientsFacade,
  clientsReducer,
  commit$,
  confirmEmail$,
  confirmEmailSuccessRedirect$,
  connectSocket$,
  createBranch$,
  addClientUser$,
  createClient$,
  createClientAgent$,
  createDeploymentConfiguration$,
  createEnvironmentVariable$,
  createFileOrDirectory$,
  createUser$,
  deleteAllEnvironmentVariables$,
  deleteBranch$,
  deleteClient$,
  deleteClientAgent$,
  deleteDeploymentConfiguration$,
  deleteEnvironmentVariable$,
  deleteFileOrDirectory$,
  deleteProvisionedServer$,
  deleteUser$,
  DeploymentsFacade,
  deploymentsReducer,
  disconnectSocket$,
  EnvFacade,
  envReducer,
  fetch$,
  FilesFacade,
  filesReducer,
  listDirectory$,
  loadBranches$,
  loadClient$,
  loadClientUsers$,
  loadClientAgent$,
  loadClientAgentCommandsFromFiles$,
  loadClientAgentCommandsLoading$,
  loadClientAgents$,
  loadClientAgentsBatch$,
  loadClients$,
  loadClientsBatch$,
  loadDeploymentConfiguration$,
  loadEnvironmentVariables$,
  loadEnvironmentVariablesBatch$,
  loadEnvironmentVariablesCount$,
  loadGitBranches$,
  loadGitDiff$,
  loadGitStatus$,
  loadJobLogs$,
  loadProvisioningProviders$,
  loadRepositories$,
  loadRunJobs$,
  loadRunLogs$,
  loadRuns$,
  loadRunStatus$,
  loadServerInfo$,
  loadServerInfoAfterProvisioning$,
  loadServerTypes$,
  loadUsers$,
  loadUsersBatch$,
  loadWorkflows$,
  login$,
  loginSuccessRedirect$,
  logout$,
  logoutSuccessRedirect$,
  moveFileOrDirectory$,
  processContainerStats$,
  provisionServer$,
  loadClientStatisticsSummary$,
  loadClientStatisticsChatIo$,
  loadClientStatisticsFilterDrops$,
  loadClientStatisticsFilterFlags$,
  loadClientStatisticsEntityEvents$,
  loadStatisticsSummary$,
  loadStatisticsChatIo$,
  loadStatisticsFilterDrops$,
  loadStatisticsFilterFlags$,
  loadStatisticsEntityEvents$,
  pull$,
  push$,
  readFile$,
  rebase$,
  register$,
  registerSuccessRedirect$,
  requestPasswordReset$,
  requestPasswordResetSuccessRedirect$,
  resetPassword$,
  resetPasswordSuccessRedirect$,
  removeClientUser$,
  resolveConflict$,
  restoreAgentLogin$,
  restoreClientContext$,
  setActiveClient$,
  SocketsFacade,
  socketsReducer,
  stageFiles$,
  StatsFacade,
  statsReducer,
  StatisticsFacade,
  statisticsReducer,
  switchBranch$,
  triggerWorkflow$,
  unstageFiles$,
  updateClient$,
  updateClientAgent$,
  updateDeploymentConfiguration$,
  updateEnvironmentVariable$,
  updateUser$,
  VcsFacade,
  vcsReducer,
  writeFile$,
} from '@forepath/framework/frontend/data-access-agent-console';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';
import { provideMonacoEditor } from 'ngx-monaco-editor-v2';
import { AuditComponent } from './audit/audit.component';
import { AgentConsoleChatComponent } from './chat/chat.component';
import { AgentConsoleConfirmEmailComponent } from './confirm-email/confirm-email.component';
import { AgentConsoleContainerComponent } from './container/container.component';
import { adminGuard } from './guards/admin.guard';
import { authGuard } from './guards/auth.guard';
import { loginGuard } from './guards/login.guard';
import { signupDisabledGuard } from './guards/signup-disabled.guard';
import { AgentConsoleLoginComponent } from './login/login.component';
import { AgentConsoleRegisterComponent } from './register/register.component';
import { AgentConsoleRequestPasswordResetConfirmationComponent } from './request-password-reset-confirmation/request-password-reset-confirmation.component';
import { AgentConsoleRequestPasswordResetComponent } from './request-password-reset/request-password-reset.component';
import { AgentConsoleResetPasswordComponent } from './reset-password/reset-password.component';
import { UserManagerComponent } from './user-manager/user-manager.component';

export const agentConsoleRoutes: Route[] = [
  {
    path: '',
    component: AgentConsoleContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'clients',
      },
      {
        path: 'login',
        component: AgentConsoleLoginComponent,
        canActivate: [loginGuard],
        title: 'Login | Agenstra',
      },
      {
        path: 'register',
        component: AgentConsoleRegisterComponent,
        canActivate: [signupDisabledGuard, loginGuard],
        title: 'Register | Agenstra',
      },
      {
        path: 'request-password-reset',
        component: AgentConsoleRequestPasswordResetComponent,
        canActivate: [loginGuard],
        title: 'Request Password Reset | Agenstra',
      },
      {
        path: 'request-password-reset-confirmation',
        component: AgentConsoleRequestPasswordResetConfirmationComponent,
        canActivate: [loginGuard],
        title: 'Password Reset Requested | Agenstra',
      },
      {
        path: 'reset-password',
        component: AgentConsoleResetPasswordComponent,
        canActivate: [loginGuard],
        title: 'Reset Password | Agenstra',
      },
      {
        path: 'confirm-email',
        component: AgentConsoleConfirmEmailComponent,
        canActivate: [loginGuard],
        title: 'Confirm Email | Agenstra',
      },
      {
        path: 'users',
        canActivate: [authGuard, adminGuard],
        component: UserManagerComponent,
        title: 'User Management | Agenstra',
      },
      {
        path: 'audit',
        canActivate: [authGuard],
        component: AuditComponent,
        title: 'Audit | Agenstra',
      },
      {
        path: 'clients',
        canActivate: [authGuard],
        title: 'Manager | Agenstra',
        children: [
          {
            path: '',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/editor',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/deployments',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
        ],
      },
      {
        path: '**',
        redirectTo: 'clients',
      },
    ],
    providers: [
      // Facades
      AgentsFacade,
      ClientsFacade,
      SocketsFacade,
      FilesFacade,
      EnvFacade,
      VcsFacade,
      StatsFacade,
      StatisticsFacade,
      DeploymentsFacade,
      // Feature states - registered at feature level for lazy loading
      provideState('clients', clientsReducer),
      provideState('agents', agentsReducer),
      provideState('sockets', socketsReducer),
      provideState('authentication', authenticationReducer),
      provideState('files', filesReducer),
      provideState('env', envReducer),
      provideState('vcs', vcsReducer),
      provideState('stats', statsReducer),
      provideState('statistics', statisticsReducer),
      provideState('deployments', deploymentsReducer),
      // Effects - only active when this feature route is loaded
      provideEffects({
        loadClients$,
        loadClientsBatch$,
        loadClient$,
        loadClientUsers$,
        addClientUser$,
        removeClientUser$,
        createClient$,
        updateClient$,
        deleteClient$,
        setActiveClient$,
        loadProvisioningProviders$,
        loadServerTypes$,
        provisionServer$,
        loadServerInfo$,
        loadServerInfoAfterProvisioning$,
        deleteProvisionedServer$,
        loadClientAgents$,
        loadClientAgentsBatch$,
        loadClientAgent$,
        loadClientAgentCommandsLoading$,
        loadClientAgentCommandsFromFiles$,
        createClientAgent$,
        updateClientAgent$,
        deleteClientAgent$,
        connectSocket$,
        disconnectSocket$,
        restoreClientContext$,
        restoreAgentLogin$,
        login$,
        loginSuccessRedirect$,
        register$,
        registerSuccessRedirect$,
        confirmEmail$,
        confirmEmailSuccessRedirect$,
        requestPasswordReset$,
        requestPasswordResetSuccessRedirect$,
        resetPassword$,
        resetPasswordSuccessRedirect$,
        logout$,
        logoutSuccessRedirect$,
        checkAuthentication$,
        readFile$,
        writeFile$,
        listDirectory$,
        createFileOrDirectory$,
        deleteFileOrDirectory$,
        moveFileOrDirectory$,
        loadEnvironmentVariables$,
        loadEnvironmentVariablesBatch$,
        loadEnvironmentVariablesCount$,
        createEnvironmentVariable$,
        clearChatHistoryOnCreateSuccess$,
        updateEnvironmentVariable$,
        clearChatHistoryOnUpdateSuccess$,
        deleteEnvironmentVariable$,
        clearChatHistoryOnDeleteSuccess$,
        deleteAllEnvironmentVariables$,
        clearChatHistoryOnDeleteAllSuccess$,
        loadGitStatus$,
        loadGitBranches$,
        loadGitDiff$,
        stageFiles$,
        unstageFiles$,
        commit$,
        push$,
        pull$,
        fetch$,
        rebase$,
        switchBranch$,
        createBranch$,
        deleteBranch$,
        resolveConflict$,
        processContainerStats$,
        loadClientStatisticsSummary$,
        loadClientStatisticsChatIo$,
        loadClientStatisticsFilterDrops$,
        loadClientStatisticsFilterFlags$,
        loadClientStatisticsEntityEvents$,
        loadStatisticsSummary$,
        loadStatisticsChatIo$,
        loadStatisticsFilterDrops$,
        loadStatisticsFilterFlags$,
        loadStatisticsEntityEvents$,
        loadDeploymentConfiguration$,
        createDeploymentConfiguration$,
        updateDeploymentConfiguration$,
        deleteDeploymentConfiguration$,
        loadRepositories$,
        loadBranches$,
        loadWorkflows$,
        loadRuns$,
        triggerWorkflow$,
        loadRunStatus$,
        loadRunLogs$,
        cancelRun$,
        loadRunJobs$,
        loadJobLogs$,
        loadUsers$,
        loadUsersBatch$,
        createUser$,
        updateUser$,
        deleteUser$,
      }),
      provideMonacoEditor(),
    ],
  },
];
