import { Route } from '@angular/router';
import {
  AgentsFacade,
  agentsReducer,
  cancelRun$,
  clearChatHistoryOnCreateSuccess$,
  clearChatHistoryOnDeleteAllSuccess$,
  clearChatHistoryOnDeleteSuccess$,
  clearChatHistoryOnUpdateSuccess$,
  ClientsFacade,
  clientsReducer,
  commit$,
  connectSocket$,
  createBranch$,
  addClientUser$,
  createClient$,
  createClientAgent$,
  createDeploymentConfiguration$,
  createEnvironmentVariable$,
  createFileOrDirectory$,
  deleteAllEnvironmentVariables$,
  deleteBranch$,
  deleteClient$,
  deleteClientAgent$,
  deleteDeploymentConfiguration$,
  deleteEnvironmentVariable$,
  deleteFileOrDirectory$,
  deleteProvisionedServer$,
  DeploymentsFacade,
  deploymentsReducer,
  disconnectSocket$,
  EnvFacade,
  envReducer,
  fetch$,
  FilesFacade,
  filesReducer,
  listDirectory$,
  loadBranches$,
  loadClient$,
  loadClientUsers$,
  loadClientAgent$,
  loadClientAgentCommandsFromFiles$,
  loadClientAgentCommandsLoading$,
  loadClientAgents$,
  loadClientAgentsBatch$,
  loadClients$,
  loadClientsBatch$,
  loadDeploymentConfiguration$,
  loadEnvironmentVariables$,
  loadEnvironmentVariablesBatch$,
  loadEnvironmentVariablesCount$,
  loadGitBranches$,
  loadGitDiff$,
  loadGitStatus$,
  loadJobLogs$,
  loadProvisioningProviders$,
  loadRepositories$,
  loadRunJobs$,
  loadRunLogs$,
  loadRuns$,
  loadRunStatus$,
  loadServerInfo$,
  loadServerInfoAfterProvisioning$,
  loadServerTypes$,
  loadWorkflows$,
  moveFileOrDirectory$,
  processContainerStats$,
  provisionServer$,
  loadClientStatisticsSummary$,
  loadClientStatisticsChatIo$,
  loadClientStatisticsFilterDrops$,
  loadClientStatisticsFilterFlags$,
  loadClientStatisticsEntityEvents$,
  loadStatisticsSummary$,
  loadStatisticsChatIo$,
  loadStatisticsFilterDrops$,
  loadStatisticsFilterFlags$,
  loadStatisticsEntityEvents$,
  pull$,
  push$,
  readFile$,
  rebase$,
  removeClientUser$,
  resolveConflict$,
  restartClientAgent$,
  restoreAgentLogin$,
  restoreClientContext$,
  setActiveClient$,
  startClientAgent$,
  stopClientAgent$,
  SocketsFacade,
  socketsReducer,
  stageFiles$,
  StatsFacade,
  statsReducer,
  StatisticsFacade,
  statisticsReducer,
  switchBranch$,
  triggerWorkflow$,
  unstageFiles$,
  updateClient$,
  updateClientAgent$,
  updateDeploymentConfiguration$,
  updateEnvironmentVariable$,
  VcsFacade,
  vcsReducer,
  writeFile$,
} from '@forepath/framework/frontend/data-access-agent-console';
import { authGuard, identityAuthProviders, identityAuthRoutes } from '@forepath/identity/frontend';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';
import { provideMonacoEditor } from 'ngx-monaco-editor-v2';
import { AuditComponent } from './audit/audit.component';
import { AgentConsoleChatComponent } from './chat/chat.component';
import { AgentConsoleContainerComponent } from './container/container.component';

export const agentConsoleRoutes: Route[] = [
  {
    path: '',
    component: AgentConsoleContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'clients',
      },
      // Identity auth routes (login, register, password reset, email confirmation, user management)
      ...identityAuthRoutes,
      {
        path: 'audit',
        canActivate: [authGuard],
        component: AuditComponent,
        title: 'Audit | Agenstra',
      },
      {
        path: 'clients',
        canActivate: [authGuard],
        title: 'Manager | Agenstra',
        children: [
          {
            path: '',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/editor',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/deployments',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
        ],
      },
      {
        path: '**',
        redirectTo: 'clients',
      },
    ],
    providers: [
      // Identity auth state (authentication reducer, facade, and auth effects)
      ...identityAuthProviders,
      // Facades
      AgentsFacade,
      ClientsFacade,
      SocketsFacade,
      FilesFacade,
      EnvFacade,
      VcsFacade,
      StatsFacade,
      StatisticsFacade,
      DeploymentsFacade,
      // Feature states - registered at feature level for lazy loading
      provideState('clients', clientsReducer),
      provideState('agents', agentsReducer),
      provideState('sockets', socketsReducer),
      provideState('files', filesReducer),
      provideState('env', envReducer),
      provideState('vcs', vcsReducer),
      provideState('stats', statsReducer),
      provideState('statistics', statisticsReducer),
      provideState('deployments', deploymentsReducer),
      // Effects - only active when this feature route is loaded
      provideEffects({
        loadClients$,
        loadClientsBatch$,
        loadClient$,
        loadClientUsers$,
        addClientUser$,
        removeClientUser$,
        createClient$,
        updateClient$,
        deleteClient$,
        setActiveClient$,
        loadProvisioningProviders$,
        loadServerTypes$,
        provisionServer$,
        loadServerInfo$,
        loadServerInfoAfterProvisioning$,
        deleteProvisionedServer$,
        loadClientAgents$,
        loadClientAgentsBatch$,
        loadClientAgent$,
        loadClientAgentCommandsLoading$,
        loadClientAgentCommandsFromFiles$,
        createClientAgent$,
        updateClientAgent$,
        deleteClientAgent$,
        startClientAgent$,
        stopClientAgent$,
        restartClientAgent$,
        connectSocket$,
        disconnectSocket$,
        restoreClientContext$,
        restoreAgentLogin$,
        readFile$,
        writeFile$,
        listDirectory$,
        createFileOrDirectory$,
        deleteFileOrDirectory$,
        moveFileOrDirectory$,
        loadEnvironmentVariables$,
        loadEnvironmentVariablesBatch$,
        loadEnvironmentVariablesCount$,
        createEnvironmentVariable$,
        clearChatHistoryOnCreateSuccess$,
        updateEnvironmentVariable$,
        clearChatHistoryOnUpdateSuccess$,
        deleteEnvironmentVariable$,
        clearChatHistoryOnDeleteSuccess$,
        deleteAllEnvironmentVariables$,
        clearChatHistoryOnDeleteAllSuccess$,
        loadGitStatus$,
        loadGitBranches$,
        loadGitDiff$,
        stageFiles$,
        unstageFiles$,
        commit$,
        push$,
        pull$,
        fetch$,
        rebase$,
        switchBranch$,
        createBranch$,
        deleteBranch$,
        resolveConflict$,
        processContainerStats$,
        loadClientStatisticsSummary$,
        loadClientStatisticsChatIo$,
        loadClientStatisticsFilterDrops$,
        loadClientStatisticsFilterFlags$,
        loadClientStatisticsEntityEvents$,
        loadStatisticsSummary$,
        loadStatisticsChatIo$,
        loadStatisticsFilterDrops$,
        loadStatisticsFilterFlags$,
        loadStatisticsEntityEvents$,
        loadDeploymentConfiguration$,
        createDeploymentConfiguration$,
        updateDeploymentConfiguration$,
        deleteDeploymentConfiguration$,
        loadRepositories$,
        loadBranches$,
        loadWorkflows$,
        loadRuns$,
        triggerWorkflow$,
        loadRunStatus$,
        loadRunLogs$,
        cancelRun$,
        loadRunJobs$,
        loadJobLogs$,
      }),
      provideMonacoEditor(),
    ],
  },
];
