services:
  frontend-billing-console-server:
    image: ghcr.io/forepath/agenstra-billing-console-server:latest
    container_name: billing-console-server
    environment:
      # Frontend server configuration
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-4500}
      NODE_ENV: ${NODE_ENV:-production}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-en}
    ports:
      - '${PORT:-4500}:${PORT:-4500}'
    networks:
      - billing-console-network
    restart: unless-stopped

networks:
  billing-console-network:
    driver: bridge
