name: Setup Windows Build Environment
description: Setup Windows build environment for the GitHub Actions workflow.

runs:
  using: 'composite'
  steps:
    - name: Install Wine, Mono, Xvfb and zip tools
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine64 wine32 mono-complete xvfb zip unzip
